### ISSUE TITLE
Error on create new study and attach new file to documents

### ISSUE THREAD

**Issue by pixelconsult** [programmierfabrik/ecs-deployment#3]
On creating a new study and attach / upload a new file

I think this is either a file rights problem or the path to the data directory does not match
Installation was in /ecs-appliance/

see install routine with following commands

ufw allow ssh
ufw allow http
ufw allow https
ufw allow 25
ufw allow 465
ufw enable

apt update
apt upgrade
apt install sudo apt-transport-https ca-certificates curl software-properties-common python3-pip
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
apt update
apt-cache policy docker-ce
apt install docker-ce
curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

mkdir /ecs-appliance
cd /ecs-appliance

git clone https://github.com/programmierfabrik/ecs
cd ecs
git checkout origin/feature/deployment-adjustments
docker build -t ecs/ecs . > build.log

cd ..
git clone https://github.com/programmierfabrik/ecs-deployment
cd ecs-deployment
./scripts/generate-env.sh appliancetest.programmierfabrik.eu

#### .env Datei editieren/anpassen

sudo docker network create ecs-reverse-proxy
sudo docker-compose up -d database
sudo docker-compose run --rm ecs.web migrate
sudo docker-compose up -d reverse-proxy
sudo docker-compose -f dummy-webserver-compose.yml up -d

#### Testing/Lets https://appliancetest.programmierfabrik.eu

sudo docker-compose -f dummy-webserver-compose.yml down

sudo docker-compose up -d mailserver
. ./.env && docker exec -e HOST=${HOST} -it ecs_mailserver \
  /bin/bash -c 'echo "test@$HOST|$(doveadm pw -s SHA512-CRYPT -u test@$HOST -p password)" >> /tmp/docker-mailserver/postfix-accounts.cf'

./scripts/setup.sh config dkim

sudo docker-compose down
sudo docker-compose up -
![Bildschirmfoto 2022-07-06 um 13 02 05](https://user-images.githubusercontent.com/34928524/177536073-2437576c-e429-4158-a8ba-a7192dca81ac.png)
![Bildschirmfoto 2022-07-06 um 13 02 14](https://user-images.githubusercontent.com/34928524/177536106-ee185df2-ad04-4555-a945-cf02ed49d288.png)
d

**Comment by halilbahar** [comment]
this was due to wrong ownership of the gpg key files. This is fixed in `feature/deployment-adjustments`.
Just rebuild the ecs docker image and everything should work.
